repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/AleksaC/terraform-py
    rev: v1.9.5
    hooks:
      - id: tf-fmt
      - id: tf-validate
